version: '3'
services:
  app:
    image: golang:1.17-bullseye
    volumes:
      - ./..:/workspace
    command: sleep infinity
    environment:
      - "GO111MODULE=on"
      - "GOPROXY=https://proxy.golang.org"
      - "GONOSUMDB=*.corp.example.com"
    cap_add: [ "SYS_PTRACE" ]
    security_opt:
      - "seccomp=unconfined"

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - 8086:8086
    environment:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
        DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
        DOCKER_INFLUXDB_INIT_ORG: iot
        DOCKER_INFLUXDB_INIT_BUCKET: users_business_events
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}

volumes:
  influxdb-data: